### PR TITLE
Fix/image panic

### LINKED ISSUE #98: All 3 examples broken (panic: runtime error: invalid memory address or nil pointer dereference)
Hello,

the 3 examples expect to be run from the root directory of the maroto repository. If they are run in another directory, they crash.

For example:

```
$ pwd
maroto/bin

$ ./sample1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb0 pc=0x11d4d5d]
goroutine 1 [running]:
github.com/jung-kurt/gofpdf.(*ImageInfoType).Width(...)
	/Users/mmolteni/sync/src/go/pkg/mod/github.com/jung-kurt/gofpdf@v1.4.2/def.go:248
...
```

The simplest possible fix is not to ignore errors :-). For example:

```
 func main() {
    m := pdf.NewMaroto(consts.Portrait, consts.A4)
    //m.SetBorder(true)

-   byteSlices, _ := ioutil.ReadFile("internal/assets/images/biplane.jpg")
+   byteSlices, err := ioutil.ReadFile("internal/assets/images/biplane.jpg")
+   if err != nil {
+       fmt.Println("Got error while opening file:", err)
+       os.Exit(1)
+   }
```

### LINKED ISSUE #99: FileImage() and other I/O functions should handle errors
Hello,

Maroto has a certain number of functions that wrap I/O operations, such as FileImage(filePathName string, prop ...props.Rect), that do not return an error.

If an error happens (simplest example: the path doesn't exist), Maroto internal state will sooner or later cause a crash (see for example #98).

I understand that gofpdf "delays" errors, but it does so in a way to keep the internal state crash-proof. Maroto should do the same.

thanks!

### LINKED ISSUE #100: Fix panic when cannot found image
**Describe the bug**
Fix nil pointer in FileImage when cannot found image.

**To Reproduce**
1. Use a FileImage with a wrong path to image.
2. Maroto will panic

**Related code:**
https://github.com/johnfercher/maroto/blob/76210eee05ffeba27b56270d0363ae741093d780/internal/examples/sample1/main.go#L58

**Expected behavior**
Maroto should return error when cannot RegisterImageOptions return nil.
https://github.com/johnfercher/maroto/blob/76210eee05ffeba27b56270d0363ae741093d780/internal/image.go#L33-L36

founded in #99

### PR DESCRIPTION
**Pull request by johnferchermeli**
**Description**
Fix FileImage from crash when cannot load image. Fix samples to not crash when executed outside of project folder.

**Related Issue**
resolve #100 
resolve #99 
resolve #98 

**Checklist**
> check with "x", if applied to your change

- [x] All methods associated with structs has ```func (s *struct) method() {}``` name style. 
- [x] Wrote unit tests for new/changed features. 
- [x] Updated docs/doc.go 
- [x] Updated pkg/pdf/example_test.go 
- [x] Updated README.md 
- [x] New public methods has comments upside them explaining what it does 
- [x] Executed `go fmt github.com/johnfercher/maroto/...` to format all files

### CODE REVIEW

File: internal/examples/zpl/main.go [hunk 1]
```diff
@@ -83,5 +83,5 @@ func main() {
 
 	m.SetBorder(false)
 
-	m.OutputFileAndClose("internal/examples/internal/pdfs/zpl.pdf")
```
Comment (marco-m) [inline internal/examples/zpl/main.go]: Ah, so this was silently failing because the path didn't exist.

File: internal/image.go [hunk 2]
```diff
@@ -29,13 +30,19 @@ func NewImage(pdf gofpdf.Pdf, math Math) *image {
 }
 
 // AddFromFile open an image from disk and add to PDF
-func (s *image) AddFromFile(path string, marginTop float64, indexCol float64, qtdCols float64, colHeight float64, prop props.Rect) {
+func (s *image) AddFromFile(path string, marginTop float64, indexCol float64, qtdCols float64, colHeight float64, prop props.Rect) (err error) {
```
Comment (marco-m) [inline internal/image.go]: Go style note: I would suggest not to use this idiom (named return values in function signature + naked returns in function body). They are confusing and error-prone. I would suggest to always explicitly return what needs to be returned, no matter how small the function is.

File: internal/image.go [hunk 3]
```diff
@@ -29,13 +30,19 @@ func NewImage(pdf gofpdf.Pdf, math Math) *image {
...
 	info := s.pdf.RegisterImageOptions(path, gofpdf.ImageOptions{
 		ReadDpi:   false,
 		ImageType: "",
 	})
 
+	if info == nil {
+		err = errors.New("Could not register image options, maybe path/name is wrong")
+		return
+	}
```
Comment (marco-m) [inline internal/image.go]: In my opinion, this best-guess attempt at giving a meaningful error message to the user is a good example of why "delaying" errors is actually worse than following Go idiomatic error handling approach :-)

I think that at least in this case we can do better, we can use gofpdf error state, something like (untested):

```
if info == nil {
    return s.pdf.Error()
}
```

this is less verbose and gives the best possible error back to the user.

File: pkg/pdf/pdf.go [hunk 4]
```diff
@@ -358,7 +358,8 @@ func (s *PdfMaroto) FileImage(filePathName string, prop ...props.Rect) {
 	qtdCols := float64(len(s.colsClosures))
 	sumOfyOffsets := s.offsetY + rectProp.Top
 
-	s.Image.AddFromFile(filePathName, sumOfyOffsets, s.rowColCount, qtdCols, s.rowHeight, rectProp)
+	err = s.Image.AddFromFile(filePathName, sumOfyOffsets, s.rowColCount, qtdCols, s.rowHeight, rectProp)
+	return
```
Comment (marco-m) [inline pkg/pdf/pdf.go]: Another place where in my opinion it would be clearer (and even simpler) to return the full value, not the naked one:

```
return s.Image.AddFromFile(filePathName, sumOfyOffsets, s.rowColCount, qtdCols, s.rowHeight, rectProp)
```

File: internal/image.go (hunk 3 above)
Comment (johnferchermeli) [reply internal/image.go]: Ok, but in this case the panic occurs because the info is nil and I access info.Width(), isn't and error from gofpdf.

File: pkg/pdf/pdf.go (hunk 4 above)
Comment (johnferchermeli) [reply pkg/pdf/pdf.go]: Make sense, I will change it :D

File: internal/image.go (hunk 2 above)
Comment (johnferchermeli) [reply internal/image.go]: Make sense, I will change it :D

File: internal/examples/zpl/main.go (hunk 1 above)
Comment (johnferchermeli) [reply internal/examples/zpl/main.go]: Make sense, I will change it.

**Comment by johnferchermeli** [comment]
@marco-m feel free to give your tips =)
